name: badiainnovations
region: nyc
services:
  - name: web
    github:
      repo: YOUR_GITHUB_USERNAME/BadiaInnovations
      branch: main
      deploy_on_push: true
    
    build_command: pnpm install && pnpm build
    
    run_command: |
      pnpm add -g serve
      serve -s dist -l 8080
    
    envs:
      - key: NODE_ENV
        value: production
    
    http_port: 8080
    
    instance_count: 1
    instance_size_slug: basic-xxs
    
    routes:
      - path: /
    
    health_check:
      http_path: /
    
    cors:
      allow_origins:
        - prefix: https://badiainnovations.dev
      allow_methods:
        - GET
        - POST
        - PUT
        - DELETE
        - OPTIONS
      allow_headers:
        - Content-Type
        - Authorization
    
    # Static asset caching
    static_sites:
      - name: assets
        source_dir: dist
        catchall_document: index.html
        output_dir: /
        routes:
          - path: /assets
        headers:
          - name: Cache-Control
            value: public, max-age=31536000, immutable
          - name: X-Content-Type-Options
            value: nosniff
